//===============AUTHENTICATION===============
//Login
export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";
//Register
export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_REGISTER_FAILURE = "AUTH_REGISTER_FAILURE";
//Session
export const AUTH_GET_STATUS = "AUTH_GET_STATUS";
export const AUTH_GET_STATUS_SUCCESS = "AUTH_GET_STATUS_SUCCESS";
export const AUTH_GET_STATUS_FAILURE = "AUTH_GET_STATUS_FAILURE";
//Logout
export const AUTH_LOGOUT = "AUTH_LOGOUT";

//===============CLASS===============
/* Student Info */
export const GET_STUDENTS_INFO = "GET_STUDENTS_INFO";
export const GET_STUDENTS_INFO_SUCCESS = "GET_STUDENTS_INFO_SUCCESS";
export const GET_STUDENTS_INFO_FAILURE = "GET_STUDENTS_INFO_FAILURE";
//Student Edit
export const STUDENT_INFO_EDIT = "STUDENT_INFO_EDIT";
export const STUDENT_INFO_EDIT_SUCCESS = "STUDENT_INFO_EDIT_SUCCESS";
export const STUDENT_INFO_EDIT_FAILURE = "STUDENT_INFO_EDIT_FAILURE";
/* Class Board*/
export const CLASS_BOARD = "CLASS_BOARD";
export const CLASS_BOARD_SUCCESS = "CLASS_BOARD_SUCCESS";
export const CLASS_BOARD_FAILURE = "CLASS_BOARD_FAILURE";
/* Class Post */
export const CLASS_POST = "CLASS_POST";
export const CLASS_POST_SUCCESS = "CLASS_POST_SUCCESS";
export const CLASS_POST_FAILURE = "CLASS_POST_FAILURE";
/*Class Edit*/
export const CLASS_EDIT_PREP = "CLASS_EDIT_PREP";
export const CLASS_EDIT = "CLASS_EDIT";
export const CLASS_EDIT_SUCCESS = "CLASS_EDIT_SUCCESS";
export const CLASS_EDIT_FAILURE = "CLASS_EDIT_FAILURE";
