//===============AUTHENTICATION===============
//Login
export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";
//Register
export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_REGISTER_FAILURE = "AUTH_REGISTER_FAILURE";
//Session
export const AUTH_GET_STATUS = "AUTH_GET_STATUS";
export const AUTH_GET_STATUS_SUCCESS = "AUTH_GET_STATUS_SUCCESS";
export const AUTH_GET_STATUS_FAILURE = "AUTH_GET_STATUS_FAILURE";
//Session
export const AUTH_UPDATE = "AUTH_UPDATE";
export const AUTH_UPDATE_SUCCESS = "AUTH_UPDATE_SUCCESS";
export const AUTH_UPDATE_FAILURE = "AUTH_UPDATE_FAILURE";
//Logout
export const AUTH_LOGOUT = "AUTH_LOGOUT";

//===============MEMOLIST===============
/* MemoList Board */
export const MEMO_LIST_POST = "MEMO_LIST_POST";
export const MEMO_LIST_POST_SUCCESS = "MEMO_LIST_POST_SUCCESS";
export const MEMO_LIST_POST_FAILURE = "MEMO_LIST_POST_FAILURE";
/* MemoList Get */
export const MEMO_LIST_GET = "MEMO_LIST_GET";
export const MEMO_LIST_GET_SUCCESS = "MEMO_LIST_GET_SUCCESS";
export const MEMO_LIST_GET_FAILURE = "MEMO_LIST_GET_FAILURE";
/* MemoList Edit */
export const MEMO_LIST_EDIT = "MEMO_LIST_EDIT";
export const MEMO_LIST_EDIT_SUCCESS = "MEMO_LIST_EDIT_SUCCESS";
export const MEMO_LIST_EDIT_FAILURE = "MEMO_LIST_EDIT_FAILURE";
/* MemoList Remove */
export const MEMO_LIST_REMOVE = "MEMO_LIST_REMOVE";
export const MEMO_LIST_REMOVE_SUCCESS = "MEMO_LIST_REMOVE_SUCCESS";
export const MEMO_LIST_REMOVE_FAILURE = "MEMO_LIST_REMOVE_FAILURE";

//===============MemoGroup===============
/* MemoGroup Board */
export const MEMO_GROUP_POST = "MEMO_GROUP_POST";
export const MEMO_GROUP_POST_SUCCESS = "MEMO_GROUP_POST_SUCCESS";
export const MEMO_GROUP_POST_FAILURE = "MEMO_GROUP_POST_FAILURE";
/* MemoGroup Get */
export const MEMO_GROUP_GET = "MEMO_GROUP_GET";
export const MEMO_GROUP_GET_SUCCESS = "MEMO_GROUP_GET_SUCCESS";
export const MEMO_GROUP_GET_FAILURE = "MEMO_GROUP_GET_FAILURE";
/* MemoGroup Edit */
export const MEMO_GROUP_EDIT = "MEMO_GROUP_EDIT";
export const MEMO_GROUP_EDIT_SUCCESS = "MEMO_GROUP_EDIT_SUCCESS";
export const MEMO_GROUP_EDIT_FAILURE = "MEMO_GROUP_EDIT_FAILURE";
/* MemoGroup Remove */
export const MEMO_GROUP_REMOVE = "MEMO_GROUP_REMOVE";
export const MEMO_GROUP_REMOVE_SUCCESS = "MEMO_GROUP_REMOVE_SUCCESS";
export const MEMO_GROUP_REMOVE_FAILURE = "MEMO_GROUP_REMOVE_FAILURE";
/* MemoGroup Remove By MemoList*/
export const MEMO_GROUP_REMOVE_BY_LIST = "MEMO_GROUP_REMOVE_BY_LIST";
export const MEMO_GROUP_REMOVE_SUCCESS_BY_LIST = "MEMO_GROUP_REMOVE_SUCCESS_BY_LIST";
export const MEMO_GROUP_REMOVE_FAILURE_BY_LIST = "MEMO_GROUP_REMOVE_FAILURE_BY_LIST";
//===============STUDENTINFO===============
/* Student Info */
export const GET_STUDENTS_INFO = "GET_STUDENTS_INFO";
export const GET_STUDENTS_INFO_SUCCESS = "GET_STUDENTS_INFO_SUCCESS";
export const GET_STUDENTS_INFO_FAILURE = "GET_STUDENTS_INFO_FAILURE";
/* Student Edit */
export const STUDENT_INFO_EDIT = "STUDENT_INFO_EDIT";
export const STUDENT_INFO_EDIT_SUCCESS = "STUDENT_INFO_EDIT_SUCCESS";
export const STUDENT_INFO_EDIT_FAILURE = "STUDENT_INFO_EDIT_FAILURE";
/* Student PW CHANGE */
export const STUDENT_INFO_PW_CHANGE = "STUDENT_INFO_PW_CHANGE";
export const STUDENT_INFO_PW_CHANGE_SUCCESS = "STUDENT_INFO_PW_CHANGE_SUCCESS";
export const STUDENT_INFO_PW_CHANGE_FAILURE = "STUDENT_INFO_PW_CHANGE_FAILURE";
/* Student Remove */
export const STUDENT_INFO_REMOVE = "STUDENT_INFO_REMOVE";
export const STUDENT_INFO_REMOVE_SUCCESS = "STUDENT_INFO_REMOVE_SUCCESS";
export const STUDENT_INFO_REMOVE_FAILURE = "STUDENT_INFO_REMOVE_FAILURE";
/* Get Students In Class */
export const STUDENTS_IN_CLASS_GET = "STUDENTS_IN_CLASS_GET";
export const STUDENTS_IN_CLASS_GET_SUCCESS = "STUDENTS_IN_CLASS_GET_SUCCESS";
export const STUDENTS_IN_CLASS_GET_FAILURE = "STUDENTS_IN_CLASS_GET_FAILURE"; 


//===============CLASS===============
/* Class Board*/
export const CLASS_BOARD = "CLASS_BOARD";
export const CLASS_BOARD_SUCCESS = "CLASS_BOARD_SUCCESS";
export const CLASS_BOARD_FAILURE = "CLASS_BOARD_FAILURE";
/* Class Post */
export const CLASS_POST = "CLASS_POST";
export const CLASS_POST_SUCCESS = "CLASS_POST_SUCCESS";
export const CLASS_POST_FAILURE = "CLASS_POST_FAILURE";
/*Class Edit*/
export const CLASS_EDIT = "CLASS_EDIT";
export const CLASS_EDIT_SUCCESS = "CLASS_EDIT_SUCCESS";
export const CLASS_EDIT_FAILURE = "CLASS_EDIT_FAILURE";
/*Class Remove*/
export const CLASS_REMOVE = "CLASS_REMOVE";
export const CLASS_REMOVE_SUCCESS = "CLASS_REMOVE_SUCCESS";
export const CLASS_REMOVE_FAILURE = "CLASS_REMOVE_FAILURE";

//===============LECTURE===============
/* Lecture Board */
export const LECTURE_POST = "LECTURE_POST";
export const LECTURE_POST_SUCCESS = "LECTURE_POST_SUCCESS";
export const LECTURE_POST_FAILURE = "LECTURE_POST_FAILURE";
/* Lecture Get */
export const LECTURE_BOARD = "LECTURE_BOARD";
export const LECTURE_BOARD_SUCCESS = "LECTURE_BOARD_SUCCESS";
export const LECTURE_BOARD_FAILURE = "LECTURE_BOARD_FAILURE";
/* Lecture Edit */
export const LECTURE_EDIT = "LECTURE_EDIT";
export const LECTURE_EDIT_SUCCESS = "LECTURE_EDIT_SUCCESS";
export const LECTURE_EDIT_FAILURE = "LECTURE_EDIT_FAILURE";
/* Lecture Remove */
export const LECTURE_REMOVE = "LECTURE_REMOVE";
export const LECTURE_REMOVE_SUCCESS = "LECTURE_REMOVE_SUCCESS";
export const LECTURE_REMOVE_FAILURE = "LECTURE_REMOVE_FAILURE";

//===============HOMEWORKINFO===============
/* Homework Board*/
export const HOMEWORK_BOARD = "HOMEWORK_BOARD";
export const HOMEWORK_BOARD_SUCCESS = "HOMEWORK_BOARD_SUCCESS";
export const HOMEWORK_BOARD_FAILURE = "HOMEWORK_BOARD_FAILURE";
/* Homework Post */
export const HOMEWORK_POST = "HOMEWORK_POST";
export const HOMEWORK_POST_SUCCESS = "HOMEWORK_POST_SUCCESS";
export const HOMEWORK_POST_FAILURE = "HOMEWORK_POST_FAILURE";
/*Homework Edit*/
export const HOMEWORK_EDIT_PREP = "HOMEWORK_EDIT_PREP";
export const HOMEWORK_EDIT = "HOMEWORK_EDIT";
export const HOMEWORK_EDIT_SUCCESS = "HOMEWORK_EDIT_SUCCESS";
export const HOMEWORK_EDIT_FAILURE = "HOMEWORK_EDIT_FAILURE";
/*Homework Remove*/
export const HOMEWORK_REMOVE = "HOMEWORK_REMOVE";
export const HOMEWORK_REMOVE_SUCCESS = "HOMEWORK_REMOVE_SUCCESS";
export const HOMEWORK_REMOVE_FAILURE = "HOMEWORK_REMOVE_FAILURE";

//===============COMMNET===============
export const GET_COMMENTS = "GET_COMMENTS";
export const APPEND_COMMENT = "APPEND_COMMENT";
export const UPDATE_COMMENT = "UPDATE_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";
export const FLASH_COMMENTS = "FLASH_COMMENTS";
